// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApCUDsqrzNiYy8rDTI6K1c9ZC_UaYHFNU',
    appId: '1:165979392171:web:497e70a2128a36fe194fee',
    messagingSenderId: '165979392171',
    projectId: 'ielts-7d51b',
    authDomain: 'ielts-7d51b.firebaseapp.com',
    databaseURL: 'https://ielts-7d51b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ielts-7d51b.firebasestorage.app',
    measurementId: 'G-84NPT22G1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIjLdC4N8sVLrpl9JjhkC_JSNIDuMWBwQ',
    appId: '1:165979392171:android:93c54d6a692f56b8194fee',
    messagingSenderId: '165979392171',
    projectId: 'ielts-7d51b',
    databaseURL: 'https://ielts-7d51b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ielts-7d51b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr_ncCXqz8yCOc7yrHzGI-7uMD5vEkXmI',
    appId: '1:165979392171:ios:902d73f4f1d678a4194fee',
    messagingSenderId: '165979392171',
    projectId: 'ielts-7d51b',
    databaseURL: 'https://ielts-7d51b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ielts-7d51b.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr_ncCXqz8yCOc7yrHzGI-7uMD5vEkXmI',
    appId: '1:165979392171:ios:902d73f4f1d678a4194fee',
    messagingSenderId: '165979392171',
    projectId: 'ielts-7d51b',
    databaseURL: 'https://ielts-7d51b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ielts-7d51b.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApCUDsqrzNiYy8rDTI6K1c9ZC_UaYHFNU',
    appId: '1:165979392171:web:635f3637444f68e8194fee',
    messagingSenderId: '165979392171',
    projectId: 'ielts-7d51b',
    authDomain: 'ielts-7d51b.firebaseapp.com',
    databaseURL: 'https://ielts-7d51b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ielts-7d51b.firebasestorage.app',
    measurementId: 'G-V9S29V50KQ',
  );
}
